/**
 * Monster data + instance types (PIXELMON_FACTORY.md §1.1, GDD §2.2).
 *
 * `Monster` is the static species template (from the Factory spec).
 * `MonsterInstance` is an individual captured creature (GDD §2.3).
 */
import type {
  AbilityID,
  EggGroup,
  EvolutionMethod,
  GrowthRate,
  MonsterID,
  MoveID,
  Nature,
  SpriteRef,
  StatusCondition,
  Type,
} from "./core.js";

/** Base stats (PIXELMON_FACTORY.md §1.1). */
export interface Stats {
  hp: number; // 1–255
  attack: number; // 5–190
  defense: number; // 5–230
  spAttack: number; // 10–194
  spDefense: number; // 20–230
  speed: number; // 5–180
}

/** A single level-up learnset entry (PIXELMON_FACTORY.md §1.1). */
export interface LevelUpMove {
  level: number; // 1–100, or 0 for evolution-only moves
  move: MoveID;
}

/** An evolution requirement (PIXELMON_FACTORY.md §1.1). */
export interface Evolution {
  to: MonsterID;
  method: EvolutionMethod;
  requirement: number | string; // level number, ItemID, MoveID, etc.
  condition?: "day" | "night" | "rain" | "snow";
}

/** Static species template generated by the Factory (PIXELMON_FACTORY.md §1.1). */
export interface Monster {
  id: MonsterID;
  name: string; // max 12 chars, TitleCase
  types: [Type, Type?] | [Type];
  baseStats: Stats;
  evYield: Partial<Stats>; // total 1–3
  abilities: AbilityID[]; // 1–3, first is primary
  hiddenAbility?: AbilityID;
  height: number; // meters, 0.1–20.0
  weight: number; // kilograms, 0.1–999.9
  genderRatio: number; // female % (0–100, -1 = genderless)
  eggGroups: EggGroup[]; // 1–2
  hatchSteps: number; // 256–10240
  growthRate: GrowthRate;
  catchRate: number; // 3–255 (lower = harder)
  baseFriendship: number; // 0–255, default 70
  baseExp: number; // 36–255
  learnset: LevelUpMove[];
  tmMoves: number[]; // TMNumber[]
  eggMoves: MoveID[];
  evolution?: Evolution[];
  pokedex: {
    category: string;
    entry: string;
  };
  sprites: {
    front: SpriteRef;
    back: SpriteRef;
    icon: SpriteRef;
    overworld: SpriteRef;
  };
}

/** IV/EV ranges (GDD §2.3). IVs are 0–31 per stat; EVs 0–255, 510 total. */
export type IVs = { [K in keyof Stats]: number };
export type EVs = Partial<Stats>;

/** A single move slot on an instance (GDD §2.3). */
export interface MoveInstance {
  id: MoveID;
  pp: number; // remaining PP
  maxPp: number; // base PP (for PP-recovery items)
}

/** Met/encounter metadata (GDD §2.3). */
export interface MetInfo {
  location: string;
  level: number;
  date: string; // ISO date
}

/** An individual captured creature (GDD §2.3). */
export interface MonsterInstance {
  uid: string; // unique instance ID
  monsterId: MonsterID;
  nickname?: string;
  level: number;
  exp: number;
  stats: Stats; // calculated from base + IVs + EVs
  ivs: IVs; // 0–31 per stat
  evs: EVs; // 0–255 per stat, 510 total
  nature: Nature;
  ability: AbilityID;
  moves: MoveInstance[]; // max 4
  hp: number; // current HP
  status: StatusCondition | null;
  friendship: number; // 0–255
  met: MetInfo;
  pokerus: boolean;
  shiny: boolean; // 1/4096 chance
}
