#include "types.hpp"

#include <algorithm>
#include <cctype>

#include "core/type_chart.inc"

namespace pm {

// ---- string <-> enum mappings ---------------------------------------------
static std::string lower(std::string_view s) {
    std::string out(s.size(), ' ');
    std::transform(s.begin(), s.end(), out.begin(),
                   [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    return out;
}

Type typeFromName(std::string_view raw) {
    const std::string key = lower(raw);
    static const char* const names[] = {
        "normal", "fire", "water", "grass", "electric", "ice", "fighting", "poison",
        "ground", "flying", "psychic", "bug", "rock", "ghost", "dragon", "dark",
        "fairy", "steel",
    };
    for (int i = 0; i < 18; ++i)
        if (names[i] == key) return static_cast<Type>(i);
    return Type::Normal;  // unknown -> safe default
}

std::string_view typeName(Type t) {
    static const char* const names[] = {
        "Normal", "Fire", "Water", "Grass", "Electric", "Ice", "Fighting", "Poison",
        "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark",
        "Fairy", "Steel",
    };
    int i = static_cast<int>(t);
    if (i < 0 || i >= 18) return "Normal";
    return names[i];
}

MoveCategory categoryFromName(std::string_view raw) {
    const std::string key = lower(raw);
    if (key == "physical") return MoveCategory::Physical;
    if (key == "special") return MoveCategory::Special;
    return MoveCategory::Status;
}

std::string_view categoryName(MoveCategory c) {
    switch (c) {
        case MoveCategory::Physical: return "Physical";
        case MoveCategory::Special:  return "Special";
        default:                     return "Status";
    }
}

GrowthRate growthFromName(std::string_view raw) {
    const std::string key = lower(raw);
    static const char* const names[] = {
        "slow", "medium-slow", "medium-fast", "fast", "erratic", "fluctuating",
    };
    for (int i = 0; i < 6; ++i)
        if (names[i] == key) return static_cast<GrowthRate>(i);
    return GrowthRate::PeriodicMid;  // medium-slow default
}

std::string_view growthName(GrowthRate g) {
    static const char* const names[] = {
        "Slow", "Medium-Slow", "Medium-Fast", "Fast", "Erratic", "Fluctuating",
    };
    int i = static_cast<int>(g);
    if (i < 0 || i >= 6) return "Medium-Slow";
    return names[i];
}

// ---- type effectiveness ----------------------------------------------------
// Reads the authoritative 18x18 matrix generated by scripts/generate-type-chart.mjs
// (row = attacker enum index, column = defender enum index).
const double (&typeChart())[18][18] {
    return g_TypeChart;
}

double typeMultiplier(Type attacker, Type defender) {
    int a = static_cast<int>(attacker);
    int d = static_cast<int>(defender);
    if (a < 0 || a >= 18 || d < 0 || d >= 18) return 1.0;
    return g_TypeChart[a][d];
}

}  // namespace pm
